server:
  port: 9090


spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cristian2926/DAD-2024-1-G02.git # ruta del repositorio git
          searchPaths: config-data
          #username:
          #password:
          default-label: main
  security:
    user:
      name: root
      password: 123456
